### PR TITLE
feat: jupyter lab 3.0 federated bundle support

### PR DESCRIPTION
**Pull request by maartenbreddels**
Replaces #40

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Uses bqplot/bqplot#1222 as a template

**Comment by maartenbreddels** [comment]
it seems that pip ignores the manifest file

**Comment by vidartf** [comment]
Thanks for this, I'm planning to do a sweep for lab 3 things next week. 👍

**Comment by vidartf** [comment]
I fixed the CI + pip build, I'll merge it for now, and the make sure that all the different dist scenarios work.

**Comment by maartenbreddels** [comment]
Great to see this merged!

**Comment by vidartf** [comment]
Thanks for getting the ball rolling :) Still some discussions on the lab issue to sort out before I feel comfortable publishing (maybe I could do an RC though? Would that help you?).

**Comment by maartenbreddels** [comment]
Yeah, I wanted to be sure things are working decently for users. There is
no hurry, an Rc would be nice, but I'm not sure I have the time to test it
soon.

Would be a good test to have bqplot, ipyvolume, pythreejs all working
through.

(from mobile phone)

**Comment by vidartf** [comment]
Figured out it was a yarn cache issue, so will try to do a release tomorrow 🚀  Will then try to set up an upgrade for pythreejs, but depends if there are any issues (I likely do not have much time).

**Pull request merged**
